# basic options

title: QuACK
description: Quantitative analysis and coding knowledge (UCB, Psychology)

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

logo: quack.png
show_downloads: true

