# basic options

title: Quantitative analysis and coding knowledge (UCB, Psychology)
description: Welcome to QuAcK. Find helpful materials for learning R for behavioral science! 

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

logo: logo.png
show_downloads: true

